# Generated by Django 4.0.4 on 2022-06-19 21:25

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('covid', '0002_remove_choice_votes_alter_question_is_active_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserVotes',
            new_name='UserVote',
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 20, 0, 25, 11, 86723), verbose_name='Дата публикации'),
        ),
    ]
