# Generated by Django 4.0.4 on 2022-06-24 17:17

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('covid', '0003_rename_uservotes_uservote_alter_question_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 24, 20, 17, 21, 434965), verbose_name='Дата публикации'),
        ),
        migrations.AlterUniqueTogether(
            name='uservote',
            unique_together={('user', 'choice')},
        ),
    ]
