# Generated by Django 4.0.4 on 2022-06-24 17:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0004_alter_question_pub_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 24, 20, 21, 53, 900864), verbose_name='Дата публикации'),
        ),
    ]
